# Nombre del microservicio
spring.application.name=ms-locales

# Puerto donde correra este microservicio
server.port=8081

# Configuracion de base de datos H2
spring.datasource.url=jdbc:h2:file:./data/dataLocales/localesDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Desactivamos la creacion automatica de tablas con Hibernate
# porque queremos usar migraciones con Flyway
spring.jpa.hibernate.ddl-auto=none

# Permite abrir la consola web de H2
spring.h2.console.enabled=true

# Activa Flyway para ejecutar scripts SQL al iniciar
spring.flyway.enabled=true

# ==========================================
# CONFIGURACION DE OBSERVABILIDAD (ACTUATOR)
# ==========================================

# Exponer endpoints de salud y metricas para Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Nombre de la aplicacion para que las metricas tengan una etiqueta clara en Grafana
management.metrics.tags.application=ms-locales